### ISSUE TITLE
publishing an electron app - private repo

### ISSUE THREAD

**Issue by akoskm** [electron-react-boilerplate/electron-react-boilerplate#2606]
I have a Github Action that should package and upload the packages to GitHub.
It's pretty much the copy of your workflow file:

<details>
<summary>realease.yml</summary>

```
name: Release

on:
  push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.14, windows-2019]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: yarn install
        run: |
          yarn install

      - name: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_AKOSKM }}
        run: |
          yarn package-ci
          yarn lint
          yarn tsc
          yarn test
          yarn build-e2e
          yarn test-e2e

```

</details>

However, it's failing with the following error:

<details>
<summary>Github Action output</summary>

```
[1] yarn build-renderer exited with code 0
  • electron-builder  version=22.8.1 os=19.6.0
  • loaded configuration  file=package.json ("build" field)
  • packaging       platform=darwin arch=x64 electron=7.1.13 appOutDir=release/mac
  • downloading     url=electron/electron@v7.1.13 electron-v7.1.13-darwin-x64.zip (download) size=64 MB parts=8
  • downloaded      url=electron/electron@v7.1.13 electron-v7.1.13-darwin-x64.zip (download) duration=1.303s
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see electron.build/code-signing allIdentities=
                                                   0 identities found
                                              
                                                Valid identities only
                                                   0 valid identities found
  • building        target=macOS zip arch=x64 file=release/MyPrivateAppDesktop-1.0.0-mac.zip
  • building        target=DMG arch=x64 file=release/MyPrivateAppDesktop-1.0.0.dmg
  • building block map  blockMapFile=release/MyPrivateAppDesktop-1.0.0.dmg.blockmap
  • publishing      publisher=Github (owner: my-private-app, project: my-private-app, version: 1.0.0)
  • uploading       file=MyPrivateAppDesktop-1.0.0.dmg.blockmap provider=GitHub
  • uploading       file=MyPrivateAppDesktop-1.0.0.dmg provider=GitHub
  • building embedded block map  file=release/MyPrivateAppDesktop-1.0.0-mac.zip
  • uploading       file=MyPrivateAppDesktop-1.0.0-mac.zip provider=GitHub
  ⨯ Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
HttpError: 404 Not Found
"method: GET url: https://api.github.com/repos/my-private-app/my-private-app/releases\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Wed, 30 Sep 2020 06:06:20 GMT",
  "content-type": "application/json; charset=utf-8",
  "content-length": "104",
  "connection": "close",
  "status": "404 Not Found",
  "x-oauth-scopes": "repo",
  "x-accepted-oauth-scopes": "repo",
  "x-github-media-type": "github.v3; format=json",
  "x-ratelimit-limit": "5000",
  "x-ratelimit-remaining": "4995",
  "x-ratelimit-reset": "1601449446",
  "x-ratelimit-used": "5",
  "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
  "access-control-allow-origin": "*",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "content-security-policy": "default-src 'none'",
  "vary": "Accept-Encoding, Accept, X-Requested-With",
  "x-github-request-id": "68E2:6798:19F4285:39BC956:5F74205C"
}
    at createHttpError (/Users/runner/work/my-private-app/my-private-app/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)
    at NodeHttpExecutor.handleResponse (/Users/runner/work/my-private-app/my-private-app/node_modules/builder-util-runtime/src/httpExecutor.ts:131:14)
    at ClientRequest.<anonymous> (/Users/runner/work/my-private-app/my-private-app/node_modules/builder-util-runtime/src/httpExecutor.ts:86:16)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:640:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9)
    at TLSSocket.Readable.push (_stream_readable.js:221:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
```

</details>

All I was able to figure out is that I need to create a personal access token https://www.electron.build/configuration/publish.html#githuboptions so I created that and added it to my private repo (that's `PAT_AKOSKM` in `realease.yml`).
