### ISSUE TITLE
Can't use custom fonts 

### ISSUE THREAD

**Issue by Ordluks** [electron-react-boilerplate/electron-react-boilerplate#3007]
## Summary

When I'm try to use .ttf font I'm see this error:
`Failed to decode downloaded font: http://localhost:1212/b5a393ec47e60111afd0.ttf`

I was downloaded this file whith opened its link in browser and I'm get empty not reading file. Font is locate in `assets/` folder.
This is scss code in my `src/renderer/App.global.scss`:

```scss
@font-face {
  font-family: 'Open Sans';
  src: url('/assets/OpenSans.ttf');
}


body {
  background: #232323;
  font: 16px 'Open Sans';
  color: white;
  overflow: hidden;
}
```
