### ISSUE TITLE
What is the difference between npm and 'npm'?

### ISSUE THREAD

**Issue by BangHyeongSik** [electron-react-boilerplate/electron-react-boilerplate#3184]
In test.yml, cache is written npm.
but, in publish.yml, cache is written 'npm'.

What is the difference between npm and 'npm'?

test.yml
```yml
#...
      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
#...
```

publish.yml
```yml
#...
      - name: Install Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: 'npm'
#...
```
