### ISSUE TITLE
Optimizing CSS is not working

### ISSUE THREAD

**Issue by 7otion** [electron-react-boilerplate/electron-react-boilerplate#3644]
MiniCssExtractPlugin does exactly what its supposed to do but CssMinimizerPlugin is not minifying the output.

## Steps to Reproduce

1. Clone the boilerplate and enable "Inspect element" functionality within menu.ts
2. Simply check Source panel in dev tools and you will see that style.css is not minified.

Current Behaviour:
```css
body {
    align-items: center;
    background: linear-gradient(200.96deg,#fedc2a -29.09%,#dd5789 51.77%,#7a2c9e 129.35%);
    color: #fff;
    display: flex;
    font-family: sans-serif;
    height: 100vh;
    justify-content: center;
    overflow-y: hidden;
    position: relative
}

button {
    appearance: none;
    background-color: #fff;
    border: none;
    border-radius: 10px;
    box-shadow: 0 8px 28px -6px #18274b1f,0 18px 88px -4px #18274b24;
    cursor: pointer;
    font-size: 1.3rem;
    opacity: .9;
    padding: 10px 20px;
    transition: all .1s ease-in
}

button:hover {
    opacity: 1;
    transform: scale(1.05)
}

li {
    list-style: none
}

a {
    height: fit-content;
    margin: 10px;
    width: fit-content
}

a,a:hover {
    text-decoration: none
}

a:hover {
    opacity: 1
}

.Hello {
    align-items: center;
    display: flex;
    justify-content: center;
    margin: 20px 0
}
```

Expected Result: (something like)
```css
.Hello,body{display:flex}body{align-items:center;background:linear-gradient(200.96deg,#fedc2a -29.09%,#dd5789 51.77%,#7a2c9e 129.35%);color:#fff;font-family:sans-serif;height:100vh;justify-content:center;overflow-y:hidden;position:relative}button{appearance:none;background-color:#fff;border:none;border-radius:10px;box-shadow:0 8px 28px -6px #18274b1f,0 18px 88px -4px #18274b24;cursor:pointer;font-size:1.3rem;opacity:.9;padding:10px 20px;transition:.1s ease-in}button:hover{opacity:1;transform:scale(1.05)}li{list-style:none}a{height:fit-content;margin:10px;width:fit-content}a,a:hover{text-decoration:none}a:hover{opacity:1}.Hello{align-items:center;justify-content:center;margin:20px 0}
```

As a sidenote when "MiniCssExtractPlugin" is removed so that style is directly outputted in head tag within <style> tags while also using cssnano as a plugin in postcss options minifying does work but ofc this is not even a workaround i just thought maybe this information would be useful.
